// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3P3U1gDv4thPp4HGXfujhE_u8Pu99fs',
    appId: '1:501618930237:web:0b7838e4f69e3d60ac3054',
    messagingSenderId: '501618930237',
    projectId: 'memora-5e473',
    authDomain: 'memora-5e473.firebaseapp.com',
    storageBucket: 'memora-5e473.firebasestorage.app',
    measurementId: 'G-8FSSYY8VY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwD_xzKK1DDy0LAsMGh8fa6lcvehfhd4o',
    appId: '1:501618930237:android:110d70a9af96576dac3054',
    messagingSenderId: '501618930237',
    projectId: 'memora-5e473',
    storageBucket: 'memora-5e473.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8-k6nRTTVbxIQyJvL3I_NTeSzowdYpg',
    appId: '1:501618930237:ios:67892f224630f60aac3054',
    messagingSenderId: '501618930237',
    projectId: 'memora-5e473',
    storageBucket: 'memora-5e473.firebasestorage.app',
    iosBundleId: 'com.example.memora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB8-k6nRTTVbxIQyJvL3I_NTeSzowdYpg',
    appId: '1:501618930237:ios:67892f224630f60aac3054',
    messagingSenderId: '501618930237',
    projectId: 'memora-5e473',
    storageBucket: 'memora-5e473.firebasestorage.app',
    iosBundleId: 'com.example.memora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI3P3U1gDv4thPp4HGXfujhE_u8Pu99fs',
    appId: '1:501618930237:web:56937d562e34ee23ac3054',
    messagingSenderId: '501618930237',
    projectId: 'memora-5e473',
    authDomain: 'memora-5e473.firebaseapp.com',
    storageBucket: 'memora-5e473.firebasestorage.app',
    measurementId: 'G-7GHC0VMW5D',
  );
}
